# Generated by Django 2.1.5 on 2019-01-31 00:13

from django.db import migrations, models
import quikruit.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuikruitAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('model_id', models.CharField(default=quikruit.mixins.id_gen, editable=False, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='active account')),
                ('is_staff', models.BooleanField(default=False, verbose_name='can access admin site')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser privileges')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date of account creation')),
            ],
            options={
                'verbose_name': 'Quikruit account',
                'verbose_name_plural': 'Quikruit accounts',
            },
        ),
    ]
