# Generated by Django 2.1.5 on 2019-02-04 12:41

from django.db import migrations, models
import quikruit.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('model_id', models.CharField(default=quikruit.mixins.id_gen, editable=False, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
